version: '3.7'
services:
  db:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: not_that_secret
      POSTGRES_USER: pixpq
      PGUSER: pixpq
      PGPASSWORD: not_that_secret
    ports:
      - "5432:5432"
volumes:
  postgres_data: